# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set the environment variables for PostgreSQL
ENV POSTGRES_USER pqztdjdw
ENV POSTGRES_PASSWORD VWvbG6Aig5zP-HuLo3YBtGyELLNa40GH
ENV POSTGRES_DB pqztdjdw

# Copy the SQL script to initialize the database
COPY init.sql /docker-entrypoint-initdb.d/

# Expose the PostgreSQL default port
EXPOSE 5432
