# Use the specified Golang version
FROM golang:1.21.3

# Set the working directory inside the container
WORKDIR /backend_dev

# Copy go mod and sum files
COPY go.mod .
COPY go.sum .

# Download dependencies
RUN go mod download

# Copy the entire project
COPY . .

# Build the Go application
RUN go build -o clinic .

# Expose the port the application runs on
EXPOSE 8080

# Command to run the executable
CMD ["./main"]
