# Use the specified Golang version
FROM golang:1.21.3

# Set the working directory inside the container
WORKDIR /backend

# Copy go mod and sum files
COPY go.mod .
COPY go.sum .

# Download dependencies
RUN go mod download

# Copy the entire project
COPY . .

# Build and install the Go application
RUN CGO_ENABLED=0 GOOS=linux go install -a -installsuffix cgo .

# Expose the port the application runs on
EXPOSE 8080

# Command to run the executable
CMD ["/go/bin/backend"]
