
version: '3'

services:
  frontend:
    image: frontend-image
    ports:
      - "49153:4200"
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    image: backend
    ports:
      - "8080:8080"
    networks:
      - my_network

  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pqztdjdw
      POSTGRES_PASSWORD: VWvbG6Aig5zP-HuLo3YBtGyELLNa40GH
      POSTGRES_DB: pqztdjdw
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
