

# Set the base image
FROM node:20.9.0

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install
# Install Angular CLI globally
RUN npm install -g @angular/cli@17.0.3

# Bundle app source
COPY . .

# Build the application
RUN npm run build

# Expose port
EXPOSE 4200 49153


# Run the application
CMD ["ng", "serve", "--host", "0.0.0.0"]
